### PR TITLE
Even smaller jpeg.

### PR DESCRIPTION
**Pull request by alokmenghrajani**
121 -> 107 bytes.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
:+1:

**Comment by divinity76** [comment]
are you sure this is a syntactically valid  jpeg?
Microsoft Paint and Windows' "photos" and [Paint.net](getpaint.net) all say it's not valid. IrfanView opens it, but crash when trying to zoom in on it 🤔 

The paint.net error reads

```
Exception:

PaintDotNet.Imaging.BadImageException (0x88982F60): Exception of type 'PaintDotNet.Imaging.BadImageException' was thrown. (ImagingError.BadImage 0x88982F60)
   at PaintDotNet.Interop.ExceptionFactory.ThrowError(Int32 hr, String message, Exception innerEx) in D:\src\pdn\src_5_0_x\Windows\Interop\ExceptionFactory.cs:line 54
   at PaintDotNet.Imaging.WICBitmapSource.CopyPixels(Void* pBuffer, Int32 bufferStride, UInt32 bufferSize, Nullable`1& srcRect) in D:\src\pdn\src_5_0_x\Windows\Imaging\WICBitmapSource.cs:line 109
   at PaintDotNet.Imaging.ThreadSafeWicFormatConverter.OnCopyPixels(Void* buffer, Int32 bufferStride, UInt32 bufferSize, RectInt32 srcRect) in D:\src\pdn\src_5_0_x\Windows.Core\Imaging\ThreadSafeWicFormatConverter.cs:line 74
   at PaintDotNet.Imaging.BitmapSourceBase.CopyPixels(Void* buffer, Int32 bufferStride, UInt32 bufferSize, Nullable`1& srcRect) in D:\src\pdn\src_5_0_x\Windows.Core\Imaging\BitmapSourceBase.cs:line 126
   at PaintDotNet.Imaging.Proxies.IBitmapSourceProxy.PaintDotNet.Imaging.IBitmapSource.CopyPixels(Void* pBuffer, Int32 bufferStride, UInt32 bufferSize, Nullable`1& srcRect)
   at PaintDotNet.Data.WicHelpers.Load(Stream input, Nullable`1& forcedContainerFormat, Nullable`1& preferredVendor, IMetadataTranscoder metadataTranscoder) in D:\src\pdn\src_5_0_x\PaintDotNet\Data\WicHelpers.cs:line 216
   at PaintDotNet.Data.JpegFileType.OnLoad(Stream input) in D:\src\pdn\src_5_0_x\PaintDotNet\Data\JpegFileType.cs:line 111
   at PaintDotNet.FileType.Load(Stream input) in D:\src\pdn\src_5_0_x\Data\FileType.cs:line 491
   at PaintDotNet.Functional.Func.Eval[T1,TRet](Func`2 f, T1 arg1) in D:\src\pdn\src_5_0_x\Fundamentals\Functional\Func.cs:line 60
```
(meaning, either are all 4 softwares above bugged, or this is not a valid jpeg)

**Comment by TPS** [comment]
The 1st 3 probably decode via same library, so same behavior.  IrfanView definitely bundles its own, but zooming a `strange` 1px image probably breaks its zoom function.  Try running against an actual JPEG utility from JPEG org itself.

**Comment by TPS** [comment]
> Try running against an actual JPEG utility from JPEG org itself.

```
➜ djpeg -debug -report -strict jpeg.jpg

libjpeg-turbo version 3.0.3 (build 20240508)
Copyright (C) 2009-2024 D. R. Commander
Copyright (C) 2015, 2020 Google, Inc.
Copyright (C) 2019-2020 Arm Limited
Copyright (C) 2015-2016, 2018 Matthieu Darbois
Copyright (C) 2011-2016 Siarhei Siamashka
Copyright (C) 2015 Intel Corporation
Copyright (C) 2013-2014 Linaro Limited
Copyright (C) 2013-2014 MIPS Technologies, Inc.
Copyright (C) 2009, 2012 Pierre Ossman for Cendio AB
Copyright (C) 2009-2011 Nokia Corporation and/or its subsidiary(-ies)
Copyright (C) 1999-2006 MIYASAKA Masaru
Copyright (C) 1999 Ken Murchison
Copyright (C) 1991-2020 Thomas G. Lane, Guido Vollbeding

Emulating The Independent JPEG Group's software, version 8d  15-Jan-2012

Start of Image
Define Quantization Table 0  precision 0
Start Of Frame 0xc9: width=1, height=1, components=1
    Component 1: 1hx1v q=0
Define Arithmetic Table 0x00: 0x10
Define Arithmetic Table 0x10: 0x05
Start Of Scan: 1 components
    Component 1: dc=0 ac=0
  Ss=0, Se=63, Ah=0, Al=0
P5
1 1
255
�End Of Image
```

**Comment by divinity76** [comment]
That checks out, thanks. (I haven't bothered sending bug reports fwiw)

**Comment by TPS** [comment]
> (I haven't bothered sending bug reports fwiw)

@divinity76 To _Microsoft_?   Arithmetic coding has been off-patent for a while now & they're aware, but don't care.

Irfan would likely take this a bit more seriously, but probably not high priority, since reproduced only under quite obscure conditions.  Can't hurt to report?

**Pull request closed without merging**
