### PR TITLE
Adds a webp file.

### PR DESCRIPTION
**Pull request by alokmenghrajani**
Webp is an image format developed by Google. The format supports lossless
as well as lossy compression. You can read more about it here:
https://developers.google.com/speed/webp/docs/riff_container

Addresses https://github.com/mathiasbynens/small/issues/24

### CODE REVIEW

**Comment by mathiasbynens** [comment]
:+1:

**Comment by shinnn** [comment]
I cannot browser it on Chrome 43.0.2334.0 canary (64-bit).

https://cdn.rawgit.com/mathiasbynens/small/master/webp.webp

Is it corrupt by any chance?

**Comment by alokmenghrajani** [comment]
Please submit Chrome bugs to https://code.google.com/p/chromium/issues/list :stuck_out_tongue:

**Comment by hexalys** [comment]
@alokmenghrajani 

So the BASE64 of that file is: "UklGRhIAAABXRUJQVlA4TAYAAAAvQWxvAGs=" right?

In terms of [webp support detection](https://developers.google.com/speed/webp/faq), Which kind is it? i.e. lossy, lossless, alpha etc?

**Comment by alokmenghrajani** [comment]
VP8L = Lossless. Yes, you have the right base64.

**Comment by landfillbaby** [comment]
pretty sure this got corrupted. needs a gitignore line. see #101

**Pull request closed without merging**
