### PR TITLE
Fixed batch file to be valid

### PR DESCRIPTION
**Pull request by TETYYS**
Fixes https://github.com/mathiasbynens/small/issues/58

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Can you elaborate? What was not valid about it before? Couldn’t it be executed?

**Comment by TETYYS** [comment]
An empty batch file produces this error message 
uncactf 1

**Comment by mathiasbynens** [comment]
What happens when you run it from `cmd.exe` directly?

**Comment by TETYYS** [comment]
Nothing, but cmd acts like a middleware, right? You could compile an empty .c file with your own compiler too but that wouldn't be really fair.

**Comment by mathiasbynens** [comment]
In my mind, `.bat` was Windows’ version of `.sh`, and the fact you could execute `.bat` files by double-clicking them was a Windows-ism. But fair enough :)

**Pull request merged**
