### PR TITLE
Add smallest possible git commit (empty)

### PR DESCRIPTION
**Pull request by davidak**
Here is a pull request with an empty git commit.

Can it get more meta?

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Incredible! 😆

**Comment by mathiasbynens** [comment]
Squashed, merged, and amended the link in 3619b149bc1af50f286cbb6e80743611c7b052b9. Thanks!

**Comment by davidak** [comment]
You destroyed the empty commit with the squash. Can you merge the correct commits?

**Comment by mathiasbynens** [comment]
🤦‍♂️ Sorry! Fixed.

**Pull request merged**
